### PR TITLE
Switch to implicit (PEP 420) namespace.

### PR DESCRIPTION
**Pull request by icemac**
Open issues:

- [x] No tests are run

### CODE REVIEW

**Comment by dataflake** [comment]
Those small changes are all that's required?

**Comment by gforcada** [comment]
While testing it at work, I noticed the same, tests do not run.

Not sure if it is connected with `zope.testrunner` 🤔

**Comment by dataflake** [comment]
The problem is indeed `zope.testrunner`, specifically the following lines linked below. It's not compatible with implicit namespace packages because it will remove those folders from the test search path that do not contain an `__init__.py`, so in this particular case it will give up in the folder `src/megrok` because that does not contain the file anymore. Commenting out those lines will lead to a noticeable slowdown finding tests, but it does find and run them.

https://github.com/zopefoundation/zope.testrunner/blob/4f9048acb7f54677e6e6890b8491e069d136a2d6/src/zope/testrunner/find.py#L295-L299

**Comment by dataflake** [comment]
After checking again it looks like the perceived slowdown doesn't really exist. So the fix is in `zope.testrunner`'s `find.find_test_files_` function. Commenting out the offending lines breaks a number of `zope.testrunner` unit/doc tests, though. Unfortunately there's nothing in the local and global namespaces at that point in the code that could identify the folder named after the shared namespace so that it could be excluded from that shortcut, just like the folder where the search starts is excluded.

**Comment by icemac** [comment]
@dataflake Thank you for digging into the issue. I created a ticket for it: https://github.com/zopefoundation/zope.testrunner/issues/160

**Comment by icemac** [comment]
@dataflake wrote:
> Those small changes are all that's required?

Yes, I think so. But it has be done for all packages in a namespace at the same time. I chose this package to try out implicit namespaces because it is the only one in its namespace.

See also https://packaging.python.org/en/latest/guides/packaging-namespace-packages/

**Comment by dataflake** [comment]
In an experiment on a different package I had to add the following to the `setup` call to make it work, otherwise the `release-check` step could not build the package:

```
      package_dir={'': 'src'},
```

**Comment by icemac** [comment]
> In an experiment on a different package I had to add the following to the `setup` call to make it work, otherwise the `release-check` step could not build the package:
> 
> ```
>       package_dir={'': 'src'},
> ```

This is what we usually do, so it is already in all `setup.py` files. It is also necessary for the `pkg_resouces` namespaces approach.

**Review by dataflake — APPROVED** [review]
I've done it the same way for my minor packages in the `dataflake` namespace and it worked out just fine. There's just a few so I changed them all at the same time and published releases. I am scared of doing this in the `zope` or `Products` namespace. That all needs to be closely coordinated for hundreds of packages.

**Comment by icemac** [comment]
@dataflake It will be a major update for all the packages. So not updating is still a possibility. And yes, it is a mayor effort, but it is nice to see that it is possible.

**Pull request merged**
